### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by serejahh** [Cleveroad/CRNetworkButton#3]
Is it an example how you write code in Cleveroad?

**Comment by MaxSimS** [comment]
Sometimes we give different tasks to our developers (no matter whether it's junior or senior developer) Everyone can upload his personal code examples but it's incorrect to consider that all of us practicing the same approach in code writing.
Of course we have some standarts in our company but it takes time to adapt personal code style to these standarts

**Comment by serejahh** [comment]
Don't you have code review? Especially for public code

**Comment by serejahh** [comment]
@MaxSimS As you can notice it took a month to get your response :)


- dispatch: https://github.com/Cleveroad/CRNetworkButton/blob/master/Example/CRNetworkButton/ViewController.swift#L66
- code style :) https://github.com/Cleveroad/CRNetworkButton/blob/master/Example/CRNetworkButton/MyCollectionViewController.swift#L26
- swift 3 enum: https://github.com/Cleveroad/CRNetworkButton/blob/master/CRNetworkButton/Classes/CRNetworkButton.swift#L12
- swift 2 enum: https://github.com/Cleveroad/CRNetworkButton/blob/master/CRNetworkButton/Classes/CRNetworkButton.swift#L36
- 800 LOC: https://github.com/Cleveroad/CRNetworkButton/blob/master/CRNetworkButton/Classes/CRNetworkButton.swift
- the method should be a bit longer: https://github.com/Cleveroad/CRNetworkButton/blob/master/CRNetworkButton/Classes/CRNetworkButton.swift#L639
